const squad = [
  {
    _id: "1",
    name: "Kim Jong Un",
    position: "ST",
    kit: 11,
    captain: true,
    partOf: "main",
    instructions: ["Ask for pass", "If he don't listen, kill him."],
  },
  {
    _id: "2",
    name: "Sheikh Hasina",
    position: "CAM",
    kit: 10,
    partOf: "main",
    instructions: ["Dribble around", "Shoot silently."],
  },
  {
    _id: "3",
    name: "Khaleda Zia",
    position: "RM",
    kit: 6,
    partOf: "reserved",
  },
  {
    _id: "4",
    name: "Narendra Modi",
    position: "RW",
    kit: 7,
    partOf: "main",
    instructions: ["Hold possession", "Avoid bad call"],
  },
  {
    _id: "5",
    name: "Imran Khan",
    position: "RCB",
    kit: 4,
    partOf: "main",
    instructions: ["Keep up the speed", "Avoid cards"],
  },
  {
    _id: "6",
    name: "Muhammad Bin Salman",
    position: "LCB",
    kit: 2,
    partOf: "main",
    instructions: ["Don't be selfish.", "Don't foul your teammate."],
  },
  {
    _id: "7",
    name: "Xi Jinping",
    position: "LW",
    kit: 13,
    partOf: "main",
    instructions: ["Dive in the box", "Injure the oponent gk"],
  },
  {
    _id: "8",
    name: "Justin Trudo",
    position: "GK",
    kit: 1,
    partOf: "main",
    instructions: [
      "Chipa mair diye acting skill dekhabi",
      "Pass ball to the both wings",
    ],
  },
  {
    _id: "9",
    name: "Joe Biden",
    position: "RCB",
    kit: 5,
    partOf: "main",
    instructions: [
      "Play one-two with the RM",
      "Opponent er striker er theng vainga dibi",
    ],
  },
  {
    _id: "10",
    name: "Benjamin Netaniyahu",
    position: "RM",
    kit: 17,
    partOf: "main",
    instructions: ["Oder box e dhuika boisha thakbi", "Call RCB for ball."],
  },
  {
    _id: "11",
    name: "Abdel Fattah Sisi",
    position: "LB",
    kit: 24,
    partOf: "main",
    instructions: ["Play long ball to RM", "Preserve stamina"],
  },
  {
    _id: "12",
    name: "Jesinda Ardern",
    position: "CDM",
    kit: 8,
    partOf: "main",
    instructions: ["Keep the ball rolling.", "Don't hold the ball."],
  },
  {
    _id: "13",
    name: "Ayatullah Khomeni",
    position: "ST",
    kit: 18,
    partOf: "sub",
    instructions: [
      "Shoot at first chance",
      "Communicate with the RW for cross.",
    ],
  },
];

export function getSquad() {
  return squad;
}
